export const siteConfig = {
  name: "Lee DongWook's Portfolio",
  authorName: "Lee DongWook",
  username: "Lee-Dongwook",
  description:
    "AI Native 프론트엔드 엔지니어. 현재 FutureWorkLab에서 제조 AI 에이전트 플랫폼을 개발하고 있습니다.",
  url: "",
  links: {
    github: "https://github.com/Lee-Dongwook",
    linkedin: "https://www.linkedin.com/in/dong-wook-lee-1095112a0",
    velog: "https://velog.io/@dlehddnr99",
    email: "dlehddnr0713@gmail.com",
  },
  ogImage: "",
  iconIco: "",
  logoIcon: "",
  keywords: [
    "Lee DongWook",
    "DongWook Lee",
    "이동욱",
    "AI Native Frontend Engineer",
    "Frontend Engineer",
    "Next.js",
    "LangGraph",
    "Multi-Agent",
    "A2UI",
    "Server-Driven UI",
    "Portfolio",
  ],
};
